fix bug:
  File "game/against_wall.rpy", line 53, in script
    label outro_against_wall(the_girl, the_location, the_object, the_round):
Exception: Required parameter the_girl has no value.


Signed-off-by: picobyte <PiC.o0.o.BytE@gmail.com>